### ISSUE TITLE
Task 01 Module2 Failes

### ISSUE THREAD

**Issue by Tylerbrown7213** [tmarfil/nginx-api-gateway-for-k8s#5]
When testing access to http://job.local:30020, I get a "Server Not Found" error. Running a k get svc shows a service on port 30020 was created.

#task_01$ k get svc
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
kubernetes      ClusterIP   10.152.183.1     <none>        443/TCP          31d
eclectic-jobs   NodePort    10.152.183.203   <none>        3000:30020/TCP   15s
myapp           NodePort    10.152.183.79    <none>        3000:30010/TCP   3s

**Comment by tmarfil** [comment]
resolved
